//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbcPersistent
{
    using System;
    using System.Collections.Generic;
    
    public partial class AckRouteSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AckRouteSet()
        {
            this.AnnalistSet = new HashSet<AnnalistSet>();
            this.ParamSet = new HashSet<ParamSet>();
        }
    
        public int Id { get; set; }
        public bool Active { get; set; }
        public Nullable<int> Ack_Id { get; set; }
        public Nullable<int> Actions_Id { get; set; }
        public Nullable<int> Enterprise_Id { get; set; }
    
        public virtual AckSet AckSet { get; set; }
        public virtual ActionsSet ActionsSet { get; set; }
        public virtual EnterpriseSet EnterpriseSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnnalistSet> AnnalistSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParamSet> ParamSet { get; set; }
    }
}
