//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbcPersistent
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditSet
    {
        public System.Guid AuditId { get; set; }
        public string IpAddress { get; set; }
        public string UserName { get; set; }
        public System.DateTime EventDate { get; set; }
        public int ElementId { get; set; }
        public string EventType { get; set; }
        public string TableName { get; set; }
        public string ColumnName { get; set; }
        public string NewValue { get; set; }
        public string OriginalValue { get; set; }
    }
}
