//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbcPersistent
{
    using System;
    using System.Collections.Generic;
    
    public partial class MethodSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MethodSet()
        {
            this.ParamSet = new HashSet<ParamSet>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public bool Active { get; set; }
        public Nullable<double> RequiredVolume { get; set; }
        public Nullable<double> MinimumVolume { get; set; }
        public string Formula { get; set; }
        public bool InternetPublish { get; set; }
        public Nullable<int> DeliverTime { get; set; }
        public Nullable<double> DetectionLimit_Value { get; set; }
        public int DetectionLimit_Decimals { get; set; }
        public Nullable<double> CuantificationLimit_Value { get; set; }
        public int CuantificationLimit_Decimals { get; set; }
        public Nullable<double> Uncertainty_Value { get; set; }
        public int Uncertainty_Decimals { get; set; }
        public Nullable<int> MaxTimeBeforeAnalysis { get; set; }
        public Nullable<int> LabDeliverTime { get; set; }
        public bool QcObj_HasQc { get; set; }
        public int QcObj_UpperLimit { get; set; }
        public int QcObj_LowerLimit { get; set; }
        public Nullable<int> ReportTime { get; set; }
        public Nullable<int> AnalysisTime { get; set; }
        public Nullable<int> AnalyticsMethod_Id { get; set; }
        public Nullable<int> Container_Id { get; set; }
        public Nullable<int> Preserver_Id { get; set; }
        public Nullable<int> Residue_Id { get; set; }
    
        public virtual AnalyticsMethodSet AnalyticsMethodSet { get; set; }
        public virtual ContainerSet ContainerSet { get; set; }
        public virtual PreserverSet PreserverSet { get; set; }
        public virtual ResidueSet ResidueSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParamSet> ParamSet { get; set; }
    }
}
