//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbcPersistent
{
    using System;
    using System.Collections.Generic;
    
    public partial class SucursalSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SucursalSet()
        {
            this.MatrixSet = new HashSet<MatrixSet>();
            this.AnnalistSet = new HashSet<AnnalistSet>();
            this.UserSet = new HashSet<UserSet>();
        }
    
        public int Id { get; set; }
        public bool Active { get; set; }
        public Nullable<int> Office_Id { get; set; }
        public Nullable<int> Region_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MatrixSet> MatrixSet { get; set; }
        public virtual OfficeSet OfficeSet { get; set; }
        public virtual RegionSet RegionSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnnalistSet> AnnalistSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserSet> UserSet { get; set; }
    }
}
