//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbcPersistent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserSet()
        {
            this.MatrixChangesSet = new HashSet<MatrixChangesSet>();
            this.SessionLogSet = new HashSet<SessionLogSet>();
        }
    
        public int Id { get; set; }
        public string UserName { get; set; }
        public string UserPassword { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
        public Nullable<int> Gender { get; set; }
        public string Photo { get; set; }
        public Nullable<bool> Active { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public System.DateTime UserCreateDate { get; set; }
        public Nullable<short> Role_RoleId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MatrixChangesSet> MatrixChangesSet { get; set; }
        public virtual RoleSet RoleSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SessionLogSet> SessionLogSet { get; set; }
    }
}
