//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbcPersistent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParameterSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ParameterSet()
        {
            this.MatrixSet = new HashSet<MatrixSet>();
            this.AckSet = new HashSet<AckSet>();
            this.GroupSet = new HashSet<GroupSet>();
            this.PackageSet = new HashSet<PackageSet>();
        }
    
        public int Id { get; set; }
        public int MaxPermitedLimit { get; set; }
        public int PerTurnCapacity { get; set; }
        public int PerWeekCapacity { get; set; }
        public string AutolabAssignedAreaKey { get; set; }
        public string AutolabAssignedAreaName { get; set; }
        public string GaramUniquekey { get; set; }
        public string GenericKeyForStatistic { get; set; }
        public Nullable<int> Analista_Id { get; set; }
        public Nullable<int> BaseParam_Id { get; set; }
        public Nullable<int> CentoCosto_Id { get; set; }
        public Nullable<int> Metodo_Id { get; set; }
        public Nullable<int> Precio_Id { get; set; }
        public Nullable<int> Unit_Id { get; set; }
    
        public virtual AnalysticsAreaSet AnalysticsAreaSet { get; set; }
        public virtual AnalystSet AnalystSet { get; set; }
        public virtual BaseParamSet BaseParamSet { get; set; }
        public virtual MethodSet MethodSet { get; set; }
        public virtual Prices Prices { get; set; }
        public virtual UnitSet UnitSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MatrixSet> MatrixSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AckSet> AckSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GroupSet> GroupSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PackageSet> PackageSet { get; set; }
    }
}
